spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/softUniWriterWebsite?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${db_username}
    password: ${db_password}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: never
  mvc:
    hiddenmethod:
      filter:
        enabled: true

keyys:
  remember-me:
    key: ${REMEMBER_ME_KEY:default-remember-me-key}

# Path: src/main/resources/application-dev.yaml
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

server:
  error:
    include-message: always
    include-stacktrace: always

mail:
    storyapp: storyapp@example.com
    host: localhost
    port: 1025
    username: ${MAIL_USER:username}
    password: ${MAIL_PASSWORD:password}